name = "Beyond"
author = "Ramon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bee9118fdb507de189889ad3e8ad024f9f3250c4cbacd251ecc5c4fe2a60b2a9"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
