name = "Beyond"
author = "Ramon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fccc74ae341d0a36d9ec743987aea6704c4008ea46af12f96ce0d958c5f401c5"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
