name = "Beyond"
author = "Ramon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5700ed0294f420e903d74820cebc547a49ad1be2f05351fad36371d383e6f80"

[versions]
forge = "47.4.9"
minecraft = "1.20.1"
